// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/gateways/qwen.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/gateways/qwen.go -destination=internal/mocks/qwen_gateway_mock.go -package=mocks QwenAPIGateway
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	entities "qwen-go-proxy/internal/domain/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQwenAPIGateway is a mock of QwenAPIGateway interface.
type MockQwenAPIGateway struct {
	ctrl     *gomock.Controller
	recorder *MockQwenAPIGatewayMockRecorder
	isgomock struct{}
}

// MockQwenAPIGatewayMockRecorder is the mock recorder for MockQwenAPIGateway.
type MockQwenAPIGatewayMockRecorder struct {
	mock *MockQwenAPIGateway
}

// NewMockQwenAPIGateway creates a new mock instance.
func NewMockQwenAPIGateway(ctrl *gomock.Controller) *MockQwenAPIGateway {
	mock := &MockQwenAPIGateway{ctrl: ctrl}
	mock.recorder = &MockQwenAPIGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQwenAPIGateway) EXPECT() *MockQwenAPIGatewayMockRecorder {
	return m.recorder
}

// ChatCompletions mocks base method.
func (m *MockQwenAPIGateway) ChatCompletions(req *entities.ChatCompletionRequest, credentials *entities.Credentials) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatCompletions", req, credentials)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatCompletions indicates an expected call of ChatCompletions.
func (mr *MockQwenAPIGatewayMockRecorder) ChatCompletions(req, credentials any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatCompletions", reflect.TypeOf((*MockQwenAPIGateway)(nil).ChatCompletions), req, credentials)
}

// GetBaseURL mocks base method.
func (m *MockQwenAPIGateway) GetBaseURL(credentials *entities.Credentials, defaultURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseURL", credentials, defaultURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBaseURL indicates an expected call of GetBaseURL.
func (mr *MockQwenAPIGatewayMockRecorder) GetBaseURL(credentials, defaultURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseURL", reflect.TypeOf((*MockQwenAPIGateway)(nil).GetBaseURL), credentials, defaultURL)
}
