version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

# ============================================
# BINARY BUILDS
# ============================================
builds:
  - id: qwen-go-proxy
    main: ./cmd/server
    binary: qwen-go-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} 
        -X main.date={{.Date}} -X main.builtBy=goreleaser

# ============================================
# ARCHIVES
# ============================================
archives:
  - id: archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  name_template: "{{.Tag}}"
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"

snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}"

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"


# ============================================
# 🔥 MULTI-ARCH DOCKER BUILD (BUILDX)
# ============================================
# Build a single multi-arch image using docker buildx which will contain both amd64 and arm64
# architectures in the same image manifest. This avoids creating separate tags for each
# architecture and ensures docker manifests consistently include both platforms.
# Uses Buildx --platform to build and push multi-platform images.
# ============================================
dockers:
  - id: proxy
    use: build
    builds:
      - qwen-go-proxy
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"
    goos: linux
    # Ensure goreleaser actually pushes the built images to the registry
    push: true
    # Optional: show full build logs in CI
    extra_build_flags:
      - --progress=plain

# The old docker_manifests block is no longer required when buildx pushes
# multi-arch images directly, so it has been removed to avoid confusion.
