version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

# ============================================
# 1) MULTI-PLATFORM BINARY BUILDS
# ============================================
builds:
  - id: qwen-go-proxy
    main: ./cmd/server
    binary: qwen-go-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
        -X main.version={{.Version}}
        -X main.commit={{.Commit}}
        -X main.date={{.Date}}
        -X main.builtBy=goreleaser

# ============================================
# 2) ARCHIVE ARTIFACTS (.tar.gz / .zip)
# ============================================
archives:
  - id: archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md

# ============================================
# 3) CHECKSUM (sha256)
# ============================================
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# ============================================
# 4) CHANGELOG FILTER
# ============================================
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

# ============================================
# 5) GITHUB RELEASE CONFIG
# ============================================
release:
  name_template: "{{ .Tag }}"
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"

# ============================================
# 6) SNAPSHOT BUILDS
# ============================================
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}"

# ============================================
# 7) MULTI-ARCH DOCKER IMAGE (BUILDX)
# ============================================
dockers:
  - id: proxy
    use: buildx           # <- WAJIB untuk multi-arch
    goos: linux
    builds:
      - qwen-go-proxy
    dockerfile: Dockerfile

    # Multi-platform docker image
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"

    push: true

    # Images that will be pushed to GHCR
    image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}:latest"

    # Optional: Make CI output clearer
    extra_build_flags:
      - "--progress=plain"

# ============================================
# 8) METADATA
# ============================================
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
